### ISSUE TITLE
New-Uninstall-Software

### ISSUE THREAD

**Issue by tp111** [PatchMyPCTeam/Community-Scripts#38]
Hi,

About Uninstall-Software.ps1:

I would like to be able to set the search hive to Both HKLM & HKCU. As is now I can only select one of them in the parameter "-HivesToSearch". In my opinion Both should be the default value and then you can specify just one of them if you wish.

It's a bit strange that -Uninstall all don't uninstall all but only searches in one of the Hives.

Also I wonder how I can parameter "-AdditionalArguments". Exactly what is it for and how can I use it. Would be nice if one could run aditional command or scripts throw that one.

**Comment by codaamok** [comment]
> I would like to be able to set the search hive to Both HKLM & HKCU. As is now I can only select one of them in the parameter "-HivesToSearch". In my opinion Both should be the default value and then you can specify just one of them if you wish.
It's a bit strange that -Uninstall all don't uninstall all but only searches in one of the Hives.

For now, you could call the script twice; once with the HKLM value and the other with the HKCU value.

> Also I wonder how I can parameter "-AdditionalArguments". Exactly what is it for and how can I use it. 

Kindly see the [comment-based help](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.3) in the code:

![image](https://user-images.githubusercontent.com/6683266/224970977-68f00916-331a-479a-abd5-7a01b00c5033.png)

For example, if the (Quiet)UninstallString value in the registry for a software did not include the silent param, you could use this argument in the script to add the silent parameter to the UninstallString when removing the software.

> Would be nice if one could run aditional command or scripts throw that one.

You could have a parent script which calls Uninstall-Software.ps1. Within your parent script, you could do anything else you wanted before or after calling Uninstall-Script.ps1.

**Comment by tp111** [comment]
Thanks, but how can I call the script twice from PMPC? I can only see option to run one script if I don't use a wrapper script.




Med vänliga hälsningar,
Thomas Persson



-------- Originalmeddelande --------
Från: Adam Cook ***@***.***>
Datum: 2023-03-14 11:24 (GMT+01:00)
Till: PatchMyPCTeam/Community-Scripts ***@***.***>
Kopia: tp111 ***@***.***>, Author ***@***.***>
Ämne: Re: [PatchMyPCTeam/Community-Scripts] New-Uninstall-Software (Issue #38)


I would like to be able to set the search hive to Both HKLM & HKCU. As is now I can only select one of them in the parameter "-HivesToSearch". In my opinion Both should be the default value and then you can specify just one of them if you wish.
It's a bit strange that -Uninstall all don't uninstall all but only searches in one of the Hives.

For now, you could call the script twice; once with the HKLM value and the other with the HKCU value.

Also I wonder how I can parameter "-AdditionalArguments". Exactly what is it for and how can I use it.

Kindly see the comment-based help<https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.3> in the code:

[image]<https://user-images.githubusercontent.com/6683266/224970977-68f00916-331a-479a-abd5-7a01b00c5033.png>

For example, if the (Quiet)UninstallString value in the registry for a software did not include the silent param, you could use this argument in the script to add the silent parameter to the UninstallString when removing the software.

Would be nice if one could run aditional command or scripts throw that one.

You could have a parent script which calls Uninstall-Software.ps1. Within your parent script, you could do anything else you wanted before or after calling Uninstall-Script.ps1.
