### ISSUE TITLE
Issue with applications that have brackets in the name

### ISSUE THREAD

**Issue by ercgoodman** [PatchMyPCTeam/Community-Scripts#76]
Hi,
I discovered an issue where the script will fail with the following error when it encounters applications that have brackets ([ or ]) in the display name.  In my case, the application is displayed in Add/Remove programs as "Remote Support Jump Client 24.1.2 [_customername_][_customerkey_].

When executing the script I receive the following error:
![image](https://github.com/user-attachments/assets/8461ba62-42b6-48a0-8599-3dc7fa0445a8)

I'm by no means an expert at Powershell but I was able to get it to work by modifying lines 84,90-92 to the following:

Replace all occurrences of the variable $subkey.PSPath with $subkey.PSPath.replace("[","`*").replace("]","`*")

After making this change, I also had to use the * character in line 32 when searching with wildcards.  For example, previously I was able to use:
[array]$appNameList = @('Chrome')
But after making my changes I now have to use:
[array]$appNameList = @('`*Chrome`*')

This is fine with me for now, but I wanted to call it to your attention in case there's a better way to handle it.

A reference page that I read through when attempting to debug:
https://stackoverflow.com/questions/54094312/how-do-i-use-square-brackets-in-a-wildcard-pattern-in-powershell-get-childitem

EDIT: In order to properly display the * character in the Github markdown, I had to escape it using the ` character.  Please note that the actual code does not use the escape character before the * symbol

**Comment by codaamok** [comment]
Ref https://github.com/PatchMyPCTeam/Community-Scripts/tree/main/Install/NotInstalledRequirement

cc @byteben

**Comment by byteben** [comment]
PR created for this, thanks @ercgoodman for making us aware of the bug
